port: 19129
mysql-host: 127.0.0.1
mysql-user: root
mysql-password:
mysql-database: hso
debug: false
indexRes: 8
indexCharPar: 1129
exp: 10
lvmax: 140
allow_ip_client: 50
time_login: 10000
event: 1
